services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: api
        ports:
            - "8000:80"
        container_name: api
        tty: true
        volumes:
            - ./storage:/app/storage
        depends_on:
            - mariadb
            - redis
        restart: unless-stopped

    redis:
        image: "${REDIS_IMAGE}"
        container_name: "${REDIS_CONTAINER_NAME}"
        hostname: "${REDIS_HOSTNAME}"
        command: redis-server --requirepass "${REDIS_PASSWORD}"
        environment:
            TZ: "${TZ}"
        volumes:
            - ./docker/storage/redis:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        user: root

    mariadb:
        image: "${MARIADB_IMAGE}"
        container_name: "${MARIADB_CONTAINER_NAME}"
        hostname: "${MARIADB_HOSTNAME}"
        environment:
            MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MARIADB_DATABASE}"
            TZ: "${TZ}"
        volumes:
            - ./docker/storage/mariadb:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MARIADB_ROOT_PASSWORD}"]
            retries: 3
            timeout: 5s
        user: root

    phpmyadmin:
        image: "${PHPMYADMIN_IMAGE}"
        container_name: "${PHPMYADMIN_CONTAINER_NAME}"
        hostname: "${PHPMYADMIN_HOSTNAME}"
        ports:
            - "5050:80"
        environment:
            PMA_HOST: "${MARIADB_HOSTNAME}"
            PMA_PMADB: phpmyadmin
            UPLOAD_LIMIT: 300m
            TZ: "${TZ}"

networks:
    default:
        external: true
        name: "${APP_DOCKER_NETWORK}"
